version: '3'

services:
  oceanhub_server:
    build:
      context: ../../
      dockerfile: ./infra/docker_dev/Dockerfile_server
    volumes:
      - ../../:/usr/src/app:consistent
    ports:
      - 5000:5000
    command: bash -c "source activate TEST && python backend/server/manage.py runserver"
