version: '3'

services:
  oceanhub-server:
    build:
      context: ../../
      dockerfile: ./infra/docker_dev/Dockerfile_server
    volumes:
      - ../../:/usr/src/app:consistent
    ports:
      - 5000:5000
    links:
      - kafka-cluster
    command: bash -c "source activate TEST && python backend/server/manage.py runserver"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka-cluster:
    image: wurstmeister/kafka:0.10.1.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "video-stream:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      # IDK what the flag for fetch.message.max.bytes is on here
      # (might need to copy the configfile over to the Kafka container)
    ports:
      - 9092:9092
    expose:
      - 9092
    hostname: kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper
