version: '3'

services:
  oceanhub_server:
    build:
      context: ../../
      dockerfile: ./infra/docker_dev/Dockerfile_server
    volumes:
      - ../../:/usr/src/app:consistent
    ports:
      - 5000:5000
    links:
      - kafka
    command: bash -c "source activate TEST && python backend/server/manage.py runserver"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:0.10.1.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "messages:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - 9092:9092
    expose:
      - 9092
    volumes:
      - kafkavolume:/var/run/docker.sock
volumes:
  kafkavolume:
