version: '3.2'

services:
  oceanhub-server:
    build:
      context: ../../
      dockerfile: ./infra/docker_dev/Dockerfile_server
    volumes:
      - ../../:/usr/src/app:consistent
    ports:
      - 5000:5000
    links:
      - kafka
    command: bash -c "source activate TEST && python backend/server/manage.py runserver"
    networks:
      - ochubnetwork
  zookeeper:
    image: bitnami/zookeeper:3.5.6
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181
    networks:
      - ochubnetwork
  kafka:
    image: bitnami/kafka:2.4.0
    environment:
      - KAFKA_CFG_PORT=9092,29092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_MESSAGE_MAX_BYTES=2000000
      - KAFKA_CFG_LOG_RETENTION_HOURS=1
        # IDK what the flag for fetch.message.max.bytes is on here
        # (might need to copy the configfile over to the Kafka container)
    ports:
      - 9092:9092
      - 29092:29092
    expose:
      - 9092
      - 29092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper
    depends_on:
      - zookeeper
    networks:
      - ochubnetwork

networks:
  ochubnetwork:
